name: Update README Stats

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch: # Allows you to run this workflow manually
  
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update WakaTime and Year Progress
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # This one line adds the year progress bar *and* your other stats
          BLOCKS: "year_progress, time, projects, langs, editors"
          
          # --- Other settings ---
          SHOW_TITLE: "true"
          TIME_RANGE: "last_7_days"
          SHOW_TIME: "true"
          SHOW_DATE: "true"
